### PR TITLE
Replace m_focus to m_button + additional fixes and big updates

### PR DESCRIPTION
**Pull request by Wolf3s**

### CODE REVIEW

**Comment by brentdc42** [comment]
Thanks for pull request, I will test it and merge next month as I'm currently away.

When I return I will also upload my development fork, that has some nice new features below but has an issue with scaling to be resolved and thread thread synchronization. If you feel like having a stab at it please do.

-control groups
-multi image control
-different resolutions
-Skin controls closer to being one to one with XBMC

**Comment by wolfysdl** [comment]
> Thanks for pull request, I will test it and merge next month as I'm currently away.
> 
> When I return I will also upload my development fork, that has some nice new features below but has an issue with scaling to be resolved and thread synchronization. If you feel like having an attempt to fix it please do.
> 
> -control groups -multi image control -different resolutions -Skin controls closer to being one to one with XBMC

Fine i will do, besides good to hear that you are still here dedicating a lot in this project, congrats man.

**Comment by wolfysdl** [comment]
Here if you really want to test this. here:
[xbmc360 m_focus.zip](https://github.com/brentdc-nz/XBMC-360/files/9227960/xbmc360.m_focus.zip)

**Comment by brentdc42** [comment]
Thanks for the binary, I can't test tho until back from work trip latter this month.

**Comment by wolfysdl** [comment]
> Thanks for pull request, I will test it and merge next month as I'm currently away.
> 
> When I return I will also upload my development fork, that has some nice new features below but has an issue with scaling to be resolved and thread synchronization. If you feel like having an attempt to fix it please do.
> 
> -control groups -multi image control -different resolutions -Skin controls closer to being one to one with XBMC

Control Groups is done however it needs some improvements my next task should be porting Phyton 2 and 3 or add multi-image control.

**Comment by brentdc42** [comment]
Thanks for attempting control groups, but it's not done correctly and missing a lot sorry, missing the camera and resolution , also CGUIWindow inherits CGUICControlGroup when done like XBMC.

I have already done most of this in my private fork, just fighting bugs with the scaling and thread sync when using the player. As previous mentioned I'm home from my trip in 1.5 weeks and will then upload this fork.

Rather than duplicate efforts you should have a swing at the those bugs, if you and I can fix them this will be a good update.

**Comment by wolfysdl** [comment]
> Thanks for attempting control groups, but it's not done correctly and missing a lot sorry, missing the camera and resolution , also CGUIWindow inherits CGUIControlGroup when done like XBMC.
> 
> I have already done most of this in my private fork, just fighting bugs with the scaling and thread sync when using the player. As previouly mentioned I'm home from my trip in 1.5 weeks and will then upload this fork.
> 
> Rather than duplicate efforts you should have a swing at the those bugs, if you and I can fix them this will be a good update.

see these two videos here that i'm testing your fork: https://youtu.be/Xbn3HFkS84M
https://youtu.be/u0XrOAZEPO4

**Comment by wolfysdl** [comment]
> Thanks for attempting control groups, but it's not done correctly and missing a lot sorry, missing the camera and resolution , also CGUIWindow inherits CGUIControlGroup when done like XBMC.
> 
> I have already done most of this in my private fork, just fighting bugs with the scaling and thread sync when using the player. As previouly mentioned I'm home from my trip in 1.5 weeks and will then upload this fork.
> 
> Rather than duplicate efforts you should have a swing at the those bugs, if you and I can fix them this will be a good update.

Well about this some code is duplicated but i should at least try to improve to add new features like phyton 2 or 3 or like you said fix some bugs snd cleanup some todos like the animation part and the mouse and keyboard support.

**Comment by brentdc42** [comment]
Thanks for the videos from the mainline, I have not uploaded my private fork to a branch yet, this is the one we need to test and fix the few issue with. This has much more complete control groups, also many other changes.

I hope to upload it when home on the 15th.

**Comment by wolfysdl** [comment]
> Thanks for the videos from the mainline, I have not uploaded my private fork to a branch yet, this is the one we need to test and fix the few issue with. This has much more complete control groups, also many other changes.
> 
> I hope to upload it when home on the 15th.

However you prefer excluding of course the Contol Groups the following stuff containing stuff: 
- Update smbv2 and his server connection.
- A massive improvment in ftp.

**Comment by brentdc-nz** [comment]
Thanks for the new pull request, I will review and merge them soon.

Here are the new features I'm working on that would be good if you want to look at still? It's very much in progress so needs many fixes and cleanup still, but if we borth work on it should be possible to get done.

Development branchlatest commit with the changes:
https://github.com/brentdc-nz/XBMC-360/commit/eee68b9726cbcb332811223eed41fed5cfc2ced1

Build with the files:
https://drive.google.com/file/d/1GSCGfxnSuPHtQ8EQyrHjHej1ycanmKko/view

**Comment by wolfysdl** [comment]
> Thanks for the new pull request, I will review and merge them soon.
> 
> Here are the new features I'm working on that would be good if you want to look at still? It's very much in progress so needs many fixes and cleanup still, but if we borth work on it should be possible to get done.
> 
> Development branchlatest commit with the changes: [eee68b9](https://github.com/brentdc-nz/XBMC-360/commit/eee68b9726cbcb332811223eed41fed5cfc2ced1)
> 
> Build with the files: https://drive.google.com/file/d/1GSCGfxnSuPHtQ8EQyrHjHej1ycanmKko/view

I'm gonna test soon as i return to my house. However i should soon adapt this commit on my pull request

**Comment by wolfysdl** [comment]
https://drive.google.com/file/d/1Tw53_HeI7Q09yc91hIexzefWbnXwNu6j/view?usp=drivesdk

**Comment by brentdc-nz** [comment]
Strange as the build works for me.

The reason you can't do anything is because the skin files need to be updated (hence why it's in the development branch and not master)! The new skin files will work more like real XBMC ones, they need to be redone as they are not compatible with the changes before the new group control.

Looking at the changes you made in your branch recently, looks like it broke it as CGUIWindow does not inherit the CGUIControl group.

Anyway, no worries, feel free to try and finish it, if not I will get around to it eventually hopefully.

**Comment by wolfysdl** [comment]
> Strange as the build works for me.
> 
> The reason you can't do anything is because the skin files need to be updated (hence why it's in the development branch and not master)! The new skin files will work more like real XBMC ones, they need to be redone as they are not compatible with the changes before the new group control.
> 
> Looking at the changes you made in your branch recently, looks like it broke it as CGUIWindow does not inherit the CGUIControl group.
> 
> Anyway, no worries, feel free to try and finish it, if not I will get around to it eventually hopefully.

Ok

**Comment by wolfysdl** [comment]
> Strange as the build works for me.
> 
> The reason you can't do anything is because the skin files need to be updated (hence why it's in the development branch and not master)! The new skin files will work more like real XBMC ones, they need to be redone as they are not compatible with the changes before the new group control.
> 
> Looking at the changes you made in your branch recently, looks like it broke it as CGUIWindow does not inherit the CGUIControl group.
> 
> Anyway, no worries, feel free to try and finish it, if not I will get around to it eventually hopefully.

Hi, I inerthited the class and i removed some useless stuff, now i should look for more stuff like nfs or ffmpeg, besides sorry for that pull request of libSDL2x i regret eternally what i did, i hope you inderstand this.

**Comment by wolfysdl** [comment]
Screenshot_20220918-083841_Brave
...

**Pull request closed without merging**
